branches:
  only:
    - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\tischda\yaml2json

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  - go get github.com/tischda/go2xunit
  - go get github.com/kardianos/govendor
  - govendor sync

build_script:
  - for /f "delims=" %%a in ('git describe --tags') do @set version=%%a
  - ps: Update-AppveyorBuild -Version $env:version
  - go build -ldflags "-X main.version=%version% -s -w"

test_script:
  - yaml2json.exe -version
  - govendor test -v -cover +local
  - govendor test -v +local | go2xunit -xunitnet > xunit-report.xml

artifacts:
  - path: yaml2json.exe
    name: yaml2json

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
